### ISSUE TITLE
The ora overtime element is partially visible on jsfiddle.net

### ISSUE THREAD

**Issue by cascading-jox** [cupcakearmy/ora#11]
Check out http://jsfiddle.net/ with ora enabled. It seems like the overtime element is partially visible when hidden. Maybe it would be possible to use display: none to hide it?

**Comment by cupcakearmy** [comment]
Good catch!
Found the issue, i was missing `box-sizing: border-box` on the root. Probably most websites have that as a default nowadays. Will update today

**Comment by cupcakearmy** [comment]
Submitted to stores, should be online today/tomorrow
